ModelTemplatesApp/urls.py
from django.conf.urls import url
from ModelTemplatesApp import views


#TEMPLATE TAGGING IT IS SO IMPORTANT!!!! FOR RELATIVE URLS, IT IS THE NAME OF THIS URLS!

app_name = 'template'

urlpatterns = [
    url(r'^$',views.template, name='template'),
    url(r'^relative/', views.relative, name= 'relative'),
    url(r'^other/', views.other, name= 'other'),
]

ModelsTemplates/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from ModelTemplatesApp import views


urlpatterns = [
    url(r'^$', views.index, name= 'index'),
    #SHOW THE USERS
    url(r'^users/', views.users),
    #SAVE NEW USERS
    url(r'^users2/', views.users2),
    #GO INSIDE OF THE ADMIN DJANGO PAGE
    url(r'^admin/', admin.site.urls),
    #DON'T DO IT NOTHING
    url(r'^help/', views.help, name= 'help'),
    #SHOW AN BASIC FORM WITH PROTECTION OF BOTS.
    url(r'^formpage/', views.form_name_view, name= 'form_name'),

#We cand add more urls from ModelTamplatesApp, we can use two URLs
#http://127.0.0.1:8000/ModelTemplatesApp/ for call the index function of the
#other file

    url(r'templates/',include('ModelTemplatesApp.urls'))

]

ModelTemplatesApp/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):
    top_name = models.CharField(max_length=264,unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic)
    name = models.CharField(max_length=264,unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage)
    date = models.DateField()

    def  __str__(self):
        return str(self.date)

class User(models.Model):
    first_name = models.CharField(max_length=50)
    last_name  = models.CharField(max_length=50)
    email  = models.EmailField(max_length=60)

ModelTemplatesApp/forms.py
from django import forms
from django.core import validators
from ModelTemplatesApp.models import User


class FormName(forms.Form):
    name=forms.CharField()
    email= forms.EmailField()
    verify_email = forms.EmailField(label='Enter your Email again')
    text = forms.CharField(widget=forms.Textarea)

    #CLEAN ALL THE DATA
    def clean(self):
        all_clean_data = super().clean()
        email= all_clean_data['email']
        vmail= all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError("MAKE SURE EMAILS MATCH")

class NewUserForm(forms.ModelForm):
    class Meta():
        model = User
        fields = '__all__'

ModelTemplatesApp/views.py
from django.shortcuts import render
from ModelTemplatesApp.models import AccessRecord, User
from . import forms
from ModelTemplatesApp.forms import NewUserForm

# Create your views here.
def index(request):
    webpages_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_records':webpages_list}
    #my_dict = {'insert_content': "HELLO I AM FROM MODELTEMPLATEAPP"}
    return render (request, 'ModelTemplatesApp/index.html', context=date_dict)

def help(request):
    my_dict = {'insert_content': "I DON'T HELP ANYBODY"}
    return render (request, 'ModelTemplatesApp/index.html', context=my_dict)

def users(request):
    users_list = User.objects.order_by('first_name')
    my_users = {'users':users_list}
    return render (request, 'ModelTemplatesApp/users.html', context=my_users)

#SAVE NEW USERS
def users2(request):
    form = NewUserForm()
    if request.method == "POST":
        form= NewUserForm(request.POST)

        if form.is_valid():
            #Save the user
            form.save(commit=True)
            #RETURN THE PAGE
            return index(request) #it canbe help(request) or something like that
        else:
            print('ERROR FORM INVALID')
    return render(request,'ModelTemplatesApp/usersForm.html',{'form':form})


#TEST FORM PRINT IN THE CONSOLE
def form_name_view(request):
    form= forms.FormName()
    if request.method == 'POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            #DO SOMETHING CODE
            print("VALIDATION SUCCESS")
            print("NAME: "+ form.cleaned_data['name'])
            print("EMAIL: "+ form.cleaned_data['email'])
            print("TEXT: "+ form.cleaned_data['text'])

    return render(request, 'ModelTemplatesApp/form_page.html',{'form':form})



#INHERANCE TEMPLATES
def template(request):

    return render(request, 'InheranceTemplates/template.html')


def other(request):
    context_dict = {'text' : 'hello world', 'number':100}
    return render(request, 'InheranceTemplates/other.html', context= context_dict)

def relative(request):
    return render(request, 'InheranceTemplates/relative_url_templates.html')

templates/InheranceTemplates/other.html
<!DOCTYPE html>


{%  extends "InheranceTemplates/template.html" %}
  {% block body_block %}
    <h1>Hi! i am other!</h1>
    <h2>This is an example of template inherint</h2>


    {{ text|cut:'wo' }}
    {{ number|add:"99" }}

  {% endblock %}

templates/InheranceTemplates/relative_url_templates.html
<!DOCTYPE html>

{%  extends "InheranceTemplates/template.html" %}
  {% block body_block %}
      <!-- THE NAME "TEMPLATE" IS LOCATED IN THE MODELTEMPLATESAPP/URL.PY
      IT WAS THE NAME OF THE app_name = 'template' -->

      <a href="{% url 'template:other' %}">link to other</a>
      <br>
      <a href="{% url 'admin:index' %}">link to admin</a>
      <br>
      <a href="{% url 'index' %}">link to index ORIGINAL</a>

  {% endblock %}

templates/InheranceTemplates/template.html
<!DOCTYPE html>
<!-- i don't know why, but this is important  -->

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <h1>Hi! this is template</h1>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'template:relative' %}">Relative</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'template:other' %}">Other</a></li>
          <li><a class="navbar-link" href="{% url 'index' %}">Index</a></li>
        </ul>
      </div>
    </nav>



    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherance -->
      {% endblock %}
    </div>
  </body>
</html>

templates/ModelTemplatesApp/form_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <title>forms</title>
    <h2></h2>
  </head>
  <body>

    <h1>Fill out the form</h1>
    <div class="container">
      <form method="POST">
        {{form.as_p}}
        {% csrf_token %}
        <input  type="submit" class="btn btn-primary"  value="Submit">
      </form>


    </div>

  </body>
</html>

templates/ModelTemplatesApp/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>Hello</title>
  </head>
  <body>
    <h1>Hello this is a test page</h1>
    <div class="djangtwo">
      {% if access_records %}
          <table>
            <thead>
              <th>Site Name</th>
              <th>Date Accessed</th>
            </thead>

          {% for acc in access_records %}
          <tr>
            <td>{{ acc.name }}</td>
            <td>{{ acc.date }}</td>
          </tr>
          {% endfor %}
          </table>
        {% else %}
          <p>NO ACCESS RECORDS FOUND!</P>
        {% endif %}

    </div>

  </body>
</html>

templates/ModelTemplatesApp/users.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Users</title>
  </head>
  <body>
    <h1>Users from my webpage</h1>
    <div class="djangtwo">
      {% if users %}
          <table>
            <thead>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Email</th>
            </thead>

          {% for usr in users %}
          <tr>
            <td>{{ usr.first_name }}</td>
            <td>{{ usr.last_name }}</td>
            <td>{{ usr.email }}</td>
          </tr>
          {% endfor %}
          </table>
        {% else %}
          <p>NO USERS FOUND!</P>
        {% endif %}

    </div>

  </body>
</html>

templates/ModelTemplatesApp/usersForm.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <title>Users form</title>
  </head>
  <body>
    <div class="container">
      <h1>Please sign up here</h1>
      <form method="POST">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>
    </div>
  </body>
</html>